net/fec_uio: drop deprecated priv->speed
Cope with upstream change
commit 64fdb808660d ("net: stmmac: remove write-only priv->speed")

drivers/net/ethernet/freescale/fec_uio.c:355:13: error: ‘struct stmmac_priv’ has no member named ‘speed’
  355 |         priv->speed = speed;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Vanshika Shukla <vanshika.shukla@nxp.com>