mxc: gpu-viv: remove set but unused 'timer' in gctaHARDWARE_SetMMU()
drivers/mxc/gpu-viv/hal/security_v1/gc_hal_ta_hardware.c:499:15: error:
variable 'timer' set but not used [-Werror,-Wunused-but-set-variable]
    gctUINT32 timer = 0;
              ^
1 error generated.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>