hotfix: net: fec_uio: fix build issue
API changed since the commit 83f55b01dd90 ("net: stmmac: rename xpcs_an_inband to default_an_inband")

../drivers/net/ethernet/freescale/fec_uio.c: In function ‘stmmac_phy_setup’:
../drivers/net/ethernet/freescale/fec_uio.c:425:38: error: ‘struct stmmac_mdio_bus_data’ has no member named ‘xpcs_an_inband’
  425 |                         mdio_bus_data->xpcs_an_inband;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>