LF 16506-1 net: ppfe: remove init_dummy_netdev
See:
commit f835bdae7167 ("net: remove init_dummy_netdev()")

drivers/staging/fsl_ppfe/pfe_hif.c:993:9: error: implicit declaration of function ‘init_dummy_netdev’ [-Werror=implicit-function-declaration]
  993 |         init_dummy_netdev(&hif->dummy_dev);
      |         ^~~~~~~~~~~~~~~~~

Reviewed-by: Wei Fang <wei.fang@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>