LF-13827-7 net: pfe: Replace strlcpy() with strscpy() for many drivers
Cope with upstream change:
commit d26270061ae6 ("string: Remove strlcpy()")

e.g.
../drivers/i2c/busses/i2c-flexio.c: In function ‘imx_flexio_i2c_master_probe’:
../drivers/i2c/busses/i2c-flexio.c:683:9: error: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Werror=implicit-function-declaration]
  683 |         strlcpy(i2c_dev->adapter.name, dev_name(i2c_dev->dev),
      |         ^~~~~~~
      |         strncpy

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>