LF-16506-2 net: pfe: change to use hrtimer_setup
Cope with upstream API change:
commit 48ad7bbfd53a ("treewide: Convert new and leftover hrtimer_init() users")

e.g.
drivers/gpu/arm/midgard/mali_kbase_kinstr_prfcnt.c: In function ‘kbase_kinstr_prfcnt_init’:
drivers/gpu/arm/midgard/mali_kbase_kinstr_prfcnt.c:1272:9: error: implicit declaration of function ‘hrtimer_init’; did you mean ‘hrtimers_init’? [-Werror=implicit-function-declaration]
 1272 |         hrtimer_init(&kinstr_ctx->dump_timer, CLOCK_MONOTONIC, HRTIMER_MODE_REL);
      |         ^~~~~~~~~~~~
      |         hrtimers_init

Reviewed-by: Wei Fang <wei.fang@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>