LF-16506-8 net: fec_uio: change to use plat_dat->phy_interface
Cope with upstream change
commit 6b0ed6a3a89c ("net: stmmac: remove mac_interface")

drivers/net/ethernet/freescale/fec_uio.c: In function ‘imx_dwmac_fix_speed’:
drivers/net/ethernet/freescale/fec_uio.c:199:36: error: ‘struct plat_stmmacenet_data’ has no member named ‘mac_interface’; did you mean ‘phy_interface’?
  199 |                         (plat_dat->mac_interface == PHY_INTERFACE_MODE_RMII) ||
      |                                    ^~~~~~~~~~~~~
      |                                    phy_interface

Reviewed-by: Vanshika Shukla <vanshika.shukla@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>