mxc: gpu-viv: remove set but unused 'shader_volt' in init_gpu_opp_table()
drivers/mxc/gpu-viv/hal/os/linux/kernel/platform/freescale/gc_hal_kernel_platform_imx.c:767:58: error:
variable 'shader_volt' set but not used [-Werror,-Wunused-but-set-variable]
        unsigned long core_freq, core_volt, shader_freq, shader_volt;
                                                         ^
1 error generated.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>