mxc: gpu-viv: delete set but unused 'timer' variable in gckCOMMAND_Stall()
In a clang-16 build with W=1 C=1, this warning is treated as an error:

drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_command.c:3609:17: error:
variable 'timer' set but not used [-Werror,-Wunused-but-set-variable]
    gctUINT     timer  = 0;
                ^

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>