LF-16020 gpu: disable page migrate temporarily
disable page migrate due to upstream commit since 6.16
3d388584d599 ("mm: convert "movable" flag in page->mapping to a page flag")

../drivers/gpu/arm/midgard/mali_kbase_mem_migrate.c: In function ‘kbase_free_pages_worker’:
../drivers/gpu/arm/midgard/mali_kbase_mem_migrate.c:158:25: error: implicit declaration of function ‘__ClearPageMovable’; did you mean ‘__ClearPageTable’? [-Werror=implicit-function-declaration]
  158 |                         __ClearPageMovable(p);
      |                         ^~~~~~~~~~~~~~~~~~
      |                         __ClearPageTable

Signed-off-by: Jiyu Yang <jiyu.yang@nxp.com>